### ISSUE TITLE
 Claude generates the wrong locator 

### ISSUE THREAD

**Issue by MummanaSubramanya** [executeautomation/mcp-playwright#6]
I attempted to input text into a username field, but it failed as Claude generated an incorrect locator. I had expected Claude to access the DOM and produce the appropriate locator. It seems that implementing RAG (Retrieval-Augmented Generation) is essential to generate the locators; without it, this tool is unlikely to be effective.

prompt: 
navigate to https://xxxxxxxxxxxxxxxx.io/user/login
enter usercode as "VASU"

actual element:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/95725eb8-5bea-4e9b-90da-e3c94e7e1a8b">

PW MCP output:
`{
  `value`: `VASU`,
  `selector`: `input[name='usercode']`
}`

**Comment by executeautomation** [comment]
Yes its expected behavior, this needs to be resolved by passing the locator for specific UI elements if there is such a case, as mentioned in the documentation https://executeautomation.github.io/mcp-playwright/docs/playwright-web/Supported-Tools, the tool is still in its infancy and needs more maturity, will be updating the features in the library soon.

Thanks for reporting

**Comment by rublev** [comment]
> I attempted to input text into a username field, but it failed as Claude generated an incorrect locator. I had expected Claude to access the DOM and produce the appropriate locator. It seems that implementing RAG (Retrieval-Augmented Generation) is essential to generate the locators; without it, this tool is unlikely to be effective.
> 
> prompt: navigate to https://xxxxxxxxxxxxxxxx.io/user/login enter usercode as "VASU"
> 
> actual element: <img alt="image" width="607" src="https://private-user-images.githubusercontent.com/25982124/393646667-95725eb8-5bea-4e9b-90da-e3c94e7e1a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0OTI5MDMsIm5iZiI6MTczNTQ5MjYwMywicGF0aCI6Ii8yNTk4MjEyNC8zOTM2NDY2NjctOTU3MjVlYjgtNWJlYS00ZTliLTkwZGEtZTNjOTRlN2UxYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE3MTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NWMzOTEzZGQ2NmEwYWI4ZWMyY2JkZDYwNzMxNDgzODcxNmYwYjhlYWMyODMxNjllMGFhZDkyMzcyZmMwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iuTaFsTMBSaPy4XJpKMXLg7G5M3eqrdmTBkExpdcfeI">
> 
> PW MCP output: `{ `value`: `VASU`, `selector`: `input[name='usercode']` }`

How would you go about implementing RAG for this?
